export SCALE_FACTOR=2
export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_SCREEN_SCALE_FACTOR=${SCALE_FACTOR}
# export GDK_SCALE=${SCALE_FACTOR}
# export ELM_SCALE=${SCALE_FACTOR}
# export WINIT_X11_SCALE_FACTOR=${SCALE_FACTOR}

