#!/bin/sh

# xrandr --screen 0 --fb 7680x2160 --dpi 192
# xrandr --output DP-2 --mode 3840x2160 --rate 144.00 --pos 0x0 --scale 1
# xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 60.00 --pos 3840x0 --scale 2

# xrandr --screen 0 --fb 3840x1080
# xrandr --output DP-2 --mode 3840x2160 --rate 144.00 --pos 0x0 --scale 0.5
# xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 60.00 --pos 1920x0 --scale 1

xrandr --output DP-2 --mode 3840x2160 --rate 144.00 --pos 0x0 --dpi 192
xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 60.00 --pos 3840x0

