#!/bin/sh

xrandr --screen 0 --fb 7680x2160
xrandr --screen 0 --output DP-2 --primary --mode 3840x2160 --rate 144.00 --pos 0x0 --scale 1
xrandr --screen 0 --output HDMI-0 --mode 1920x1080 --rate 60.00 --pos 3840x0 --scale 2
xrandr --screen 0 --dpi 172

~/.fehbg

